# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='main_page',
            field=models.BooleanField(default=True, verbose_name='На главную'),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='text',
            field=models.TextField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок акции'),
        ),
    ]
