# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 07:37
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_auto_20170207_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Полное описание'),
        ),
    ]
