version: '2'

services:
  caimandb:
    image: postgres
    container_name: caimanadmin_db_1
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/pgdata
  caimanweb:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    container_name: caimanadmin
    ports:
      - "8000:8000"
    depends_on:
      - caimandb

  caimanadminer:
     image: adminer
     ports:
           - 8880:8080
