# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок новости')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата для вывода')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала показа')),
                ('end_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Дата завершения показа')),
                ('main_page', models.BooleanField(default=False, verbose_name='На главную')),
                ('file', models.ImageField(blank=True, null=True, upload_to='news', verbose_name='Изображение')),
            ],
            options={
                'verbose_name_plural': 'Новости',
                'verbose_name': 'Новость',
            },
        ),
    ]
