# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 07:37
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст новости'),
        ),
    ]
