# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170209_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='news',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='news',
            name='main_page',
        ),
        migrations.RemoveField(
            model_name='news',
            name='start_date',
        ),
        migrations.AddField(
            model_name='news',
            name='small_text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Текст новости на главную'),
        ),
    ]
