# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-09 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180209_1554'),
        ('news', '0004_auto_20180125_1446'),
    ]

    operations = [
    ]
