# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-16 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180212_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='file_news',
            field=models.ImageField(blank=True, null=True, upload_to='file_news', verbose_name='Изображение для карусели новостей'),
        ),
    ]
