# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 12:51
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='file',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='gallery', verbose_name='Изображение'),
        ),
    ]
