# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 10:54
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20170310_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='file',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='gallery', verbose_name='Обложка для галлереи 250X250'),
        ),
    ]
