# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20170317_1628'),
        ('gallery', '0005_auto_20170317_1630'),
    ]

    operations = [
    ]
