# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 15:22
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20170208_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealers',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание'),
        ),
    ]
