# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_auto_20170309_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealers',
            options={'ordering': ['num'], 'verbose_name': 'Диллер', 'verbose_name_plural': 'Диллеры'},
        ),
        migrations.AddField(
            model_name='dealers',
            name='num',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
