# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название меню')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='Оставьте пустым для использования названия страницы', max_length=255, verbose_name='Название в меню')),
                ('my_order', models.PositiveIntegerField(default=0)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('menu', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='page.Menu')),
            ],
            options={
                'ordering': ['my_order'],
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('in_menus', models.BooleanField(default=True, verbose_name='Показывать в меню')),
                ('title', models.CharField(default='', max_length=1000, verbose_name='Заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=1000, verbose_name='Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=1000, verbose_name='Keywords')),
                ('menu_title', models.CharField(blank=True, help_text='Оставьте пустым для использования названия страницы', max_length=255, null=True, verbose_name='Название в меню')),
                ('slug', models.SlugField(blank=True, help_text='Только английские буквы, цифры и знаки минус и подчеркивание.', unique=True, verbose_name='Имя для url')),
                ('login_required', models.BooleanField(default=False, help_text='Если выбрано, то только залогиненный пользователь может просматривать страницу', verbose_name='Требуется логин')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='page.Page', verbose_name='Родительский элемент')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.AddField(
            model_name='menusection',
            name='page',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Page', verbose_name='Страница'),
        ),
        migrations.AddField(
            model_name='menusection',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='page.MenuSection', verbose_name='Родительский элемент'),
        ),
    ]
