# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
    ]
