# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20161216_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placeholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название плейсхолдера')),
            ],
        ),
    ]
