# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_placeholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='placeholder',
        ),
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.SlugField(default='mainmenu', help_text='Только английские буквы, цифры и знаки минус и подчеркивание.', unique=True, verbose_name='Имя для использования в шаблоне'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='in_menus',
            field=models.BooleanField(default=True, verbose_name='Опубликовать'),
        ),
    ]
