# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_auto_20170126_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, help_text="Только английские буквы, цифры и знаки минус и подчеркивание. <br><a id='set_main_page'>Главная страница</a>", unique=True, verbose_name='Имя для url'),
        ),
    ]
