# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_carousel_carouselslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='carousel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.Carousel', verbose_name='Карусель для страницы'),
        ),
    ]
