# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_page_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='slug',
            field=models.SlugField(default=0, help_text='Только английские буквы, цифры и знаки минус и подчеркивание.', unique=True, verbose_name='Имя для использования в шаблоне'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carousel',
            name='template',
            field=models.IntegerField(choices=[(0, 'carousel.html')], default=0),
        ),
    ]
