# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_auto_20170209_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone1', models.CharField(blank=True, default='', max_length=200, verbose_name='Телефонный номер 1')),
                ('phone2', models.CharField(blank=True, default='', max_length=200, verbose_name='Телефонный номер 2')),
                ('email1', models.EmailField(blank=True, max_length=254, verbose_name='E-mail 1')),
                ('email2', models.EmailField(blank=True, max_length=254, verbose_name='E-mail 2')),
                ('maindres', models.CharField(blank=True, default='', max_length=200, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
