# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-12 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_auto_20170613_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='citys',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Городов на главную'),
        ),
        migrations.AddField(
            model_name='setting',
            name='clients',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Клиентов на главную'),
        ),
        migrations.AddField(
            model_name='setting',
            name='orders',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Заказов на главную'),
        ),
        migrations.AddField(
            model_name='setting',
            name='partners',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Партнеров на главную'),
        ),
        migrations.AddField(
            model_name='setting',
            name='shops',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Магазинов на главную'),
        ),
    ]
