# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-13 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_auto_20180212_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='back_color',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Цвет в формате #FFFFFF'),
        ),
        migrations.AddField(
            model_name='setting',
            name='back_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='category', verbose_name='Фон для сайта'),
        ),
        migrations.AddField(
            model_name='setting',
            name='back_resize',
            field=models.BooleanField(default=False, verbose_name='Растянуть вертикально'),
        ),
    ]
