# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-01 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0016_auto_20180213_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='main_back_color',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Цвет фона контейнера в формате #FFFFFF'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='back_color',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Цвет фона в формате #FFFFFF'),
        ),
    ]
