# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-06 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_auto_20180301_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Наименование баннера')),
                ('banner_image', sorl.thumbnail.fields.ImageField(blank=True, upload_to='banners', verbose_name='Картинка для баннера')),
                ('banner_link', models.CharField(blank=True, default='', max_length=200, verbose_name='Ссылка с баннера')),
                ('banner_file', models.FileField(blank=True, upload_to='banners', verbose_name='Файл для скачивания')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры в раздел продукция',
            },
        ),
    ]
