# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-13 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0019_auto_20180313_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='link_1_link',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='URL первой ссылки'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='link_1_text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Текст первой ссылки'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='link_1_title',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Название первой ссылки'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='link_2_link',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='URL второй ссылки'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='link_2_text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Текст второй ссылки'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='link_2_title',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Название второй ссылки'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='link_3_link',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='URL третьей ссылки'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='link_3_text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Текст третьей ссылки'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='link_3_title',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Название третьей ссылки'),
        ),
    ]
