# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-28 14:01
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0020_auto_20180313_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='link_2_file',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='links', verbose_name='Картинка второй ссылки 370X180'),
        ),
    ]
