# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20170607_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_image',
            name='item_variation',
        ),
        migrations.AddField(
            model_name='item_image',
            name='item',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='shop.Item'),
        ),
    ]
