# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 15:17
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('title', models.CharField(default='', max_length=1000, verbose_name='Название')),
                ('meta_description', models.CharField(blank=True, max_length=1000, verbose_name='Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=1000, verbose_name='Keywords')),
                ('slug', models.SlugField(blank=True, help_text='Только английские буквы, цифры и знаки минус и подчеркивание.', unique=True, verbose_name='Имя для url')),
                ('file', sorl.thumbnail.fields.ImageField(blank=True, upload_to='category', verbose_name='Обложка для категории 250X250')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.Category', verbose_name='Родительский элемент')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('title', models.CharField(default='', max_length=1000, verbose_name='Название')),
                ('meta_description', models.CharField(blank=True, max_length=1000, verbose_name='Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=1000, verbose_name='Keywords')),
                ('slug', models.SlugField(blank=True, help_text='Только английские буквы, цифры и знаки минус и подчеркивание.', unique=True, verbose_name='Имя для url')),
                ('file', sorl.thumbnail.fields.ImageField(blank=True, upload_to='category', verbose_name='Обложка для категории 250X250')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание')),
                ('status', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('offer', models.BooleanField(default=False, verbose_name='Показывать в спецпредложениях')),
                ('offer_name1', models.CharField(default='', max_length=200, verbose_name='Наименование бренд')),
                ('offer_name2', models.CharField(default='', max_length=200, verbose_name='Наименование модель')),
                ('offer_text_price', models.CharField(default='', max_length=200, verbose_name='Цена текст')),
                ('offer_text_cost', models.CharField(default='', max_length=200, verbose_name='Цена')),
                ('offer_text1', models.CharField(default='', max_length=200, verbose_name='Строка описания 1:')),
                ('offer_text2', models.CharField(default='', max_length=200, verbose_name='Строка описания 2:')),
                ('category', models.ManyToManyField(to='shop.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Item_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000, verbose_name='Название')),
                ('file', models.ImageField(upload_to='shop', verbose_name='Изображение')),
                ('num', models.IntegerField(blank=True, db_index=True, default=0, verbose_name='Порядковый номер')),
            ],
            options={
                'ordering': ['num'],
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Item_variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('vendor_code', models.CharField(blank=True, max_length=255, verbose_name='Артикул')),
                ('default_variation', models.BooleanField(default=False, verbose_name='Вариация по умолчанию')),
                ('stock', models.IntegerField(default=0, verbose_name='На складе')),
                ('price_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена 1')),
                ('price_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена 2')),
                ('price_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена 3')),
                ('num', models.IntegerField(blank=True, db_index=True, default=0, verbose_name='Порядковый номер')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Item')),
            ],
            options={
                'ordering': ['num'],
                'verbose_name': 'Вариация',
                'verbose_name_plural': 'Вариации',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая стоимость')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата редактирования')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('cols', models.IntegerField(blank=True, default=0, verbose_name='Количество')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Item_variation')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Товар заказа',
                'verbose_name_plural': 'Товары заказа',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('num', models.IntegerField(default=0, verbose_name='Порядковый номер')),
            ],
            options={
                'ordering': ['num'],
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Status', verbose_name='Текущий статус'),
        ),
        migrations.AddField(
            model_name='item_image',
            name='item_variation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Item_variation'),
        ),
    ]
