# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='level',
        ),
        migrations.RemoveField(
            model_name='item',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='item',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tree_id',
        ),
    ]
