# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170330_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_image',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Название'),
        ),
    ]
