# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20170331_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='content_mall',
            field=models.CharField(blank=True, default='', max_length=800, verbose_name='Краткое описание'),
        ),
    ]
