# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20170331_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='default_status',
            field=models.BooleanField(default=False, verbose_name='Статус заказа при создании'),
        ),
    ]
