# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20170309_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='offer',
            field=models.BooleanField(default=False, verbose_name='Показывать в спецпредложениях'),
        ),
    ]
