# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20170309_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item_image',
            options={'ordering': ['num'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='item_variation',
            options={'ordering': ['num'], 'verbose_name': 'Вариация', 'verbose_name_plural': 'Вариации'},
        ),
    ]
