# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20170607_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_variation',
            name='price_3',
        ),
        migrations.AlterField(
            model_name='item_variation',
            name='price_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Розничная цена'),
        ),
        migrations.AlterField(
            model_name='item_variation',
            name='price_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оптовая цена'),
        ),
    ]
