# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20170320_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='offer',
            field=models.BooleanField(default=False, verbose_name='Показывать в спецпредложениях'),
        ),
        migrations.AddField(
            model_name='item',
            name='offer_name1',
            field=models.CharField(default='', max_length=200, verbose_name='Наименование бренд'),
        ),
        migrations.AddField(
            model_name='item',
            name='offer_name2',
            field=models.CharField(default='', max_length=200, verbose_name='Наименование модель'),
        ),
        migrations.AddField(
            model_name='item',
            name='offer_text',
            field=models.TextField(default='', verbose_name='Описание предложения'),
        ),
        migrations.AddField(
            model_name='item',
            name='offer_text_cost',
            field=models.CharField(default='', max_length=200, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='item',
            name='offer_text_price',
            field=models.CharField(default='', max_length=200, verbose_name='Цена текст'),
        ),
    ]
