# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20170320_1449'),
        ('shop', '0005_item_offer'),
    ]

    operations = [
    ]
