# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_status_default_status'),
        ('shop', '0006_auto_20170613_1223'),
    ]

    operations = [
    ]
