# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20170613_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='min_offer',
            field=models.IntegerField(blank=True, db_index=True, default=1, verbose_name='Минимальная партия'),
        ),
    ]
