# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20170321_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='offer_text',
        ),
        migrations.AlterField(
            model_name='item',
            name='offer_text_cost',
            field=models.CharField(default='', max_length=200, verbose_name='Строка описания 2:'),
        ),
    ]
