# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_item_min_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='view_ppc',
            field=models.BooleanField(default=True, verbose_name='Показывать РРЦ оптовикам'),
        ),
    ]
