# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_item_view_ppc'),
        ('shop', '0007_merge_20170613_1451'),
    ]

    operations = [
    ]
