# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20170321_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='offer_text1',
            field=models.CharField(default='', max_length=200, verbose_name='Строка описания 1:'),
        ),
        migrations.AddField(
            model_name='item',
            name='offer_text2',
            field=models.CharField(default='', max_length=200, verbose_name='Строка описания 2:'),
        ),
        migrations.AlterField(
            model_name='item',
            name='offer_text_cost',
            field=models.CharField(default='', max_length=200, verbose_name='Цена'),
        ),
    ]
