# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_merge_20170613_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_variation',
            name='stock_text',
            field=models.CharField(default='', max_length=255, verbose_name='Когда ожидается'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='item_variation',
            name='stock',
            field=models.IntegerField(choices=[(0, 'Нет в наличии'), (1, 'На складе'), (2, 'Ожидается')], default=1, verbose_name='На складе'),
        ),
    ]
