# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20170613_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_variation',
            name='stock_text',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Когда ожидается'),
        ),
    ]
