# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20170329_1836'),
        ('shop', '0010_auto_20170321_1731'),
    ]

    operations = [
    ]
