# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_merge_20170330_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='offer_text',
        ),
    ]
