# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-16 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20170613_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='view_ppc',
        ),
    ]
