# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-19 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_item_view_ppc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['num'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['num'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='category',
            name='num',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
        ),
        migrations.AddField(
            model_name='item',
            name='num',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
