# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-25 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20170726_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='min_lot',
            field=models.IntegerField(default=1, verbose_name='Множитель для товара'),
        ),
    ]
