# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-10 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20170710_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='field',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='adres',
            field=models.CharField(default='', max_length=1000, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='', max_length=1000, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(default='', max_length=1000, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='inn',
            field=models.CharField(default='', max_length=1000, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='', max_length=1000, verbose_name='Ваше имя'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='', max_length=1000, verbose_name='Телефон'),
        ),
    ]
