# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-05 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_item_new_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='kpp',
            field=models.CharField(default=False, max_length=1000, verbose_name='КПП'),
        ),
    ]
