# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20170712_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='min_offer',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Минимальная партия'),
        ),
    ]
