# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-05 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_userprofile_kpp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='kpp',
            field=models.CharField(default='', max_length=1000, verbose_name='КПП'),
        ),
    ]
