# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-05 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20180305_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bank',
            field=models.CharField(default='', max_length=1000, verbose_name='Наименование банка'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bik',
            field=models.CharField(default='', max_length=1000, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ks',
            field=models.CharField(default='', max_length=1000, verbose_name='К/C'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='orgn',
            field=models.CharField(default='', max_length=1000, verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rs',
            field=models.CharField(default='', max_length=1000, verbose_name='Р/C'),
        ),
    ]
