# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-05 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20180305_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='new_flag',
            field=models.IntegerField(default=0, verbose_name='Показывать как новинку'),
        ),
    ]
