# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-16 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_treecash'),
    ]

    operations = [
        migrations.AddField(
            model_name='treecash',
            name='price_from_anon',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цены от анонимный'),
        ),
        migrations.AddField(
            model_name='treecash',
            name='price_to_anon',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цены до анонимный'),
        ),
    ]
