# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-11 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20180730_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code1c',
            field=models.IntegerField(default=0, verbose_name='Код базы'),
        ),
    ]
