# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-11 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_category_code1c'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_variation',
            name='in_stock',
            field=models.IntegerField(default=0, verbose_name='Количество на складе (шт.)'),
        ),
    ]
