# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-11 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_item_variation_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_variation',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название'),
        ),
    ]
